### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by fellipeamedeiros** [krull/docker-janus#10]
Good morning,

What i need to change to make the server run on https? For example https://url.com:8088

Best regards,
Fellipe M.

**Comment by RodrigoRVieira** [comment]
Hi Felipe!

You should put a Nginx as a reverse proxy to redirect requests to Janus listening on 80.

There are known issues on Janus when listening over SSL.

Regards,

Rodrigo R. Vieira

**Comment by fellipeamedeiros** [comment]
Hello Rodrigo, how are you?

I’m trying to run on Amazon EC2 or EBS, do you have any link showing how to use ngix as a reverse proxy?

Best regards,
Fellipe M.

Em 22 de fev de 2018, à(s) 13:31, McBacker <notifications@github.com<mailto:notifications@github.com>> escreveu:


Hi Felipe!

You should put a Nginx as a reverse proxy to redirect requests to Janus listening on 80.

There are known issues on Janus when listening over SSL.

Regards,

Rodrigo R. Vieira

**Comment by RodrigoRVieira** [comment]
I'm ok, thanks!

Just follow the documentation.

https://www.nginx.com/resources/admin-guide/reverse-proxy/

Should look like this:

location / {
    proxy_pass http://localhost:80;
}

Regards,

Rodrigo R. Vieira

**Comment by fellipeamedeiros** [comment]
but nginx will not conflict with apache?

Best regards,
Fellipe M.

**Comment by RodrigoRVieira** [comment]
Not really, just take care of routes and ports.

Grab Nginx image on Docker Hub and start playing.

**Comment by ruddell** [comment]
You can also configure apache2 as the reverse proxy if you are already using it, see the "Deploying Janus behind a web frontend" section of https://janus.conf.meetecho.com/docs/deploy.html

**Comment by fellipeamedeiros** [comment]
Hello guys, good night!

Thanks for the help. Works perfectly.

Best regards,
Fellipe M.

Em 22 de fev de 2018, à(s) 19:10, Jon Ruddell <notifications@github.com<mailto:notifications@github.com>> escreveu:


You can also configure apache2 as the reverse proxy if you are already using it, see the "Deploying Janus behind a web frontend" section of https://janus.conf.meetecho.com/docs/deploy.html

**Comment by krull** [comment]
Hey guys! Thanks for the help @McBacker @ruddell ! Apologies for the tardy reply!

Yes, a reverse proxy is needed to handle https as `libmicrohttpd` has an issue [with CPU load per noted here](https://github.com/meetecho/janus-gateway/blob/master/transports/janus_http.c#L18).

Anyways, I'd rather have nginx handle all outbound facing connections via https, and just have my docker instance mapped to localhost that nginx can communicate with.

All the best,

krull
