### ISSUE TITLE
What is the recommended way to run this image?

### ISSUE THREAD

**Issue by realflight1** [krull/docker-janus#11]
I am probably missing something really trivial, but what is the recommended way to run this image when pulling from `hub.docker.com`? If I just `docker run` it janus complains about missing configuration files:

    $ docker run mcroth/docker-janus:latest
    Janus commit: 63d7ea37ebba5d40ddc4bc374210814c26537e92
    Compiled on:  Mon Oct 23 19:14:47 UTC 2017
    
    Error reading/parsing the configuration file, going on with the defaults and the command line arguments
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.cfg'... error 2 (No such file or directory)
    ---------------------------------------------------
      Starting Meetecho Janus (WebRTC Gateway) v0.2.6
    ---------------------------------------------------
    
    Checking command line arguments...
    Debug/log level is 4
    Debug/log timestamps are disabled
    Debug/log colors are enabled
    Using 172.17.0.2 as local IP...
    [WARN] Token based authentication disabled
    Initializing recorder code
    Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, IPv6 support disabled)
    TURN REST API backend: (disabled)
    [WARN] Janus is deployed on a private address (172.17.0.2) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
    BUNDLE is NOT going to be forced
    rtcp-mux is NOT going to be forced
    Crypto: OpenSSL pre-1.1.0
    [WARN] No cert/key specified, autogenerating some...
    ICE handles watchdog started
    Fingerprint of our certificate: 33:4A:5F:0B:08:30:56:7F:98:05:8D:12:13:8E:18:FE:35:1A:6A:42:06:C7:96:B3:23:C5:34:29:C6:F4:A7:44
    Event handler plugins folder: /opt/janus/lib/janus/events
    [WARN] Event handlers support disabled
    Plugins folder: /opt/janus/lib/janus/plugins
    Loading plugin 'libjanus_textroom.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.textroom.cfg'... error 2 (No such file or directory)
    JANUS TextRoom plugin initialized!
    Loading plugin 'libjanus_audiobridge.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.audiobridge.cfg'... error 2 (No such file or directory)
    JANUS AudioBridge plugin initialized!
    Loading plugin 'libjanus_streaming.so'...
    Sessions watchdog started
    TextRoom watchdog started
    AudioBridge watchdog started
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.streaming.cfg'... error 2 (No such file or directory)
    JANUS Streaming plugin initialized!
    Loading plugin 'libjanus_nosip.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.nosip.cfg'... error 2 (No such file or directory)
    JANUS NoSIP plugin initialized!
    Loading plugin 'libjanus_recordplay.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.recordplay.cfg'... error 2 (No such file or directory)
    [FATAL] [plugins/janus_recordplay.c:janus_recordplay_init:709] No recordings path specified, giving up...
    [WARN] The 'janus.plugin.recordplay' plugin could not be initialized
    Loading plugin 'libjanus_voicemail.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.voicemail.cfg'... error 2 (No such file or directory)
    [ERR] [utils.c:janus_mkdir:218] Error creating folder ./html
    [ERR] [plugins/janus_voicemail.c:janus_voicemail_init:361] Permission denied[WARN] The 'janus.plugin.voicemail' plugin could not be initialized
    Loading plugin 'libjanus_videoroom.so'...
    NoSIP watchdog started
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.videoroom.cfg'... error 2 (No such file or directory)
    JANUS VideoRoom plugin initialized!
    Loading plugin 'libjanus_videocall.so'...
    Streaming watchdog started
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.videocall.cfg'... error 2 (No such file or directory)
    JANUS VideoCall plugin initialized!
    Loading plugin 'libjanus_echotest.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.echotest.cfg'... error 2 (No such file or directory)
    JANUS EchoTest plugin initialized!
    Loading plugin 'libjanus_sip.so'...
    VideoRoom watchdog started
    EchoTest watchdog started
    VideoCall watchdog started
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.plugin.sip.cfg'... error 2 (No such file or directory)
    JANUS SIP plugin initialized!
    Transport plugins folder: /opt/janus/lib/janus/transports
    Loading transport plugin 'libjanus_http.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.transport.http.cfg'... error 2 (No such file or directory)
    [WARN] No HTTP/HTTPS server started, giving up...
    [WARN] The 'janus.transport.http' plugin could not be initialized
    Loading transport plugin 'libjanus_pfunix.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.transport.pfunix.cfg'... error 2 (No such file or directory)
    [WARN] No Unix Sockets server started, giving up...
    [WARN] The 'janus.transport.pfunix' plugin could not be initialized
    Loading transport plugin 'libjanus_websockets.so'...
    [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.transport.websockets.cfg'... error 2 (No such file or directory)
    [WARN] No WebSockets server started, giving up...
    [2018/03/19 17:10:13:8822] NOTICE: lws_context_destroy: ctx (nil)
    [WARN] The 'janus.transport.websockets' plugin could not be initialized
    [FATAL] [janus.c:main:4314] No Janus API transport is available... enable at least one and restart Janus
    
Thanks!

**Comment by krull** [comment]
Hi,

[The conf files are in the host part](https://github.com/krull/docker-janus/tree/master/janus/etc/janus) of this git repo. Have a look at the [docker-compose.yml](https://github.com/krull/docker-janus/blob/master/docker-compose.yml) file for an example on how to do a docker run with the `-v` option.

**Comment by VincentSC** [comment]
I think the question is how to get a minimal working Janus-server via Docker, not how to build a tailored Janus-server.

**Comment by maheshmahadevan** [comment]
I have the same issue , i dont see how this was answered.. Are we really missing something in the steps...
