### ISSUE TITLE
Question: How to turn off certain Plugins?

### ISSUE THREAD

**Issue by sirlukecoop** [krull/docker-janus#16]
If I didn't want the EchoTest plugin enabled, how would I turn it off? I tried removing the .cfg file in etc/janus folder, but it was still enabled.

Thanks!

**Comment by ruddell** [comment]
Did you try disabling it in janus.cfg?
https://github.com/krull/docker-janus/blob/2f0407060e571a8a8712b2fa58379d4ab989e699/janus/etc/janus/janus.cfg#L154

**Comment by sirlukecoop** [comment]
Doh. I'm an idiot - didn't see that portion.

That worked, thanks!
