### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ghost** [krull/docker-janus#2]
I created and started container with:
`docker-compose up -d`
but i get exit status = -1

Container log file contains:
`{"log":"Error opening log file /var/log/janus.log: Permission denied\n","stream":"stdout","time":"2017-03-14T14:14:21.874209353Z"}`

Any help?

**Comment by krull** [comment]
@yuledev check your perms on the host... make certain UID/GID 999 is mapped correspondingly on the host as the docker instance uses UID/GID 999 internally.

What I usually do is the following, on the host:

```
groupadd -g 999 docker
useradd -m -u 999 -g 999 docker
```
This ensure that host/container docker user is 1:1.

Your mileage may vary.

**Comment by roadev** [comment]
> @yuledev check your perms on the host... make certain UID/GID 999 is mapped correspondingly on the host as the docker instance uses UID/GID 999 internally.
> 
> What I usually do is the following, on the host:
> 
> ```
> groupadd -g 999 docker
> useradd -m -u 999 -g 999 docker
> ```
> 
> This ensure that host/container docker user is 1:1.
> 
> Your mileage may vary.

I still face the same problem as @yuledev  :/

**Comment by lnogueir** [comment]
Why is this closed? There is no clear solution

**Comment by lekhnath** [comment]
I am also facing the same issue

**Comment by alsiPanda** [comment]
I am facing the same issue. the groupadd and useradd commands did not help
