### ISSUE TITLE
janus-gateway exited with code 1

### ISSUE THREAD

**Issue by karthik-aiyer-fujixerox** [krull/docker-janus#3]
Hello,

I was trying to test out the docker-compose.yml present in this repo so that I could eventually use janus for my project. But the service seems to be failing every time I launch it. PFA the generated logs.
[janus_log.txt](https://github.com/krull/docker-janus/files/846507/janus_log.txt)

**Comment by krull** [comment]
@karthik-aiyer-fujixerox kindly use pastebin next time. Its just best practice around here at github so that we don't have to download additional log files.

Nevertheless, it seem that you are not running the corresponding cfg files mapped within the docker-compose.yml file. From your log:

```
?[36mjanus-gateway    |?[0m [ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.cfg'... error 2 (No such file or dir
tory)
```
Last I checked with my latest commit, doing a `docker-compose up` results in a working instance.

**Comment by krull** [comment]
@karthik-aiyer-fujixerox in addition latest version of docker-compose I tested is below:

```
root@mcroth:~/sandbox/docker-janus# docker-compose -v
docker-compose version 1.11.2, build dfed245
```

**Comment by karthik-aiyer-fujixerox** [comment]
@krull ... The volumes that have been defined don't seem to be linking properly. The following is my docker information:

```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
```

Is there any specific version of docker that is required to make this docker work?

**Comment by krull** [comment]
@karthik-aiyer-fujixerox I have these latest version:

```
root@mcroth:~# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

In addition, make certain [this](https://github.com/krull/docker-janus/issues/2#issuecomment-287350283) is true to your environment.

Hope this helps.

**Comment by Fuzzyma** [comment]
@karthik-aiyer-fujixerox I have the same problem. Were you able to solve this?
